CREATE table myusers (
                         id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         firstname varchar(255) NOT NULL,
                         lastname  varchar(255) NOT NULL,
                         age       int check ( age > 0 )
);